### ISSUE TITLE
New version is needed with corrected elm-package.json.

### ISSUE THREAD

**Issue by rafaelbfs** [TheSeamau5/GraphicsEngine#4]
Hello,
It seems that the elm-package or elm-get fetches the files from the latest tag and not from master. Therefore the master branch must be merged with the current tag 1.1.1 or a new tag must be created from master. Otherwise elm-package will still download from 1.1.1 which is broken because of changes in the webgl related dependencies.

**Comment by TheSeamau5** [comment]
I've just pushed some new commits and bumped the version. From my end everything seems to work. Please check on your end and hopefully, if all is good, I can close this issue. Thanks for your help.

(While you're at it, you might want to check the new `test.elm` file. It incorporates some of the new upcoming features in the project. So, for the first time, there is lighting in the project. :smile: )

**Comment by rafaelbfs** [comment]
Sorry about the delay. The corporate proxy didn't allow access to the elm repo. It works perfectly. Closing issue. 
Thanks!
